Report = 'Events/Aggregates 1-10-60 Min Intervals w text2'
SQL = '''SELECT
    DATE_TIME              AS DATE_TIME
,   NODE_ID                AS NODE_ID
,   trim(IP_ADDRESS_ID)    AS IP_ADDRESS_ID
,   trim(COMPONENT_NAME)   AS COMPONENT_NAME
,   trim(SEVERITY_NAME)    AS SEVERITY_NAME
,   EVENT_ID               AS EVENT_ID
,   COUNT(EVENT_ID)        AS EVENT_COUNTS
,   MIN(TEXT)              AS TEXT_EXAMPLE
FROM (SELECT
        CASE '%s'
        WHEN '1' THEN
            CAST(CAST((GEN_TS_LCT) AS DATE) AS TIMESTAMP(0))
            + CAST(HOUR((GEN_TS_LCT)) AS INTERVAL HOUR)
            + CAST(CAST(SUBSTRING(CAST(GEN_TS_LCT AS CHAR(26)) FROM 15 FOR 2) AS INTEGER) AS INTERVAL MINUTE)
        WHEN '10' THEN
            CAST(CAST((GEN_TS_LCT) AS DATE) AS TIMESTAMP(0))
            + CAST(HOUR((GEN_TS_LCT)) AS INTERVAL HOUR)
            + CAST(CAST(SUBSTRING(CAST(GEN_TS_LCT AS CHAR(26)) FROM 15 FOR 1) AS INTEGER)*10 AS INTERVAL MINUTE)
        WHEN '60' THEN
            CAST(CAST((GEN_TS_LCT) AS DATE) AS TIMESTAMP(0))
            + CAST(HOUR((GEN_TS_LCT)) AS INTERVAL HOUR)
        END
        AS DATE_TIME
,       NODE_ID
,       IP_ADDRESS_ID
,       COMPONENT_NAME
,       SEVERITY_NAME
,       EVENT_ID
,       TEXT
    FROM
        MANAGEABILITY.INSTANCE_REPOSITORY.EVENT_TEXT_1
    WHERE
            GEN_TS_LCT BETWEEN ? AND ?
    ) AS A
GROUP BY
    DATE_TIME
,   NODE_ID
,   IP_ADDRESS_ID
,   COMPONENT_NAME
,   SEVERITY_NAME
,   EVENT_ID
ORDER BY
    DATE_TIME
,   NODE_ID
,   IP_ADDRESS_ID
,   COMPONENT_NAME
,   SEVERITY_NAME
,   EVENT_ID
FOR READ UNCOMMITTED ACCESS IN SHARE MODE''' % 1


