Report = 'Session/Slow LDAPs 1-10-60 Min Intervals'
SQL = '''SELECT
    DATE_TIME                                                   AS DATE_TIME
,   COUNT(SESSION_START_TS_LCT)                                 AS SLOW_SESSIONS
,   SUM(TOTAL_LOGIN_ELAPSED_TIME_MCSEC) / 1000000               AS SLOW_LOGIN_SECS
,   SUM(LDAP_LOGIN_ELAPSED_TIME_MCSEC) / 1000000                AS SLOW_LDAP_SECS
,   SUM(SEARCH_CONNECTION_ELAPSED_TIME_MCSEC) / 1000000         AS SLOW_SEARCH_CONNECTION_SECS
,   SUM(SEARCH_ELAPSED_TIME_MCSEC) / 1000000                    AS SLOW_SEARCH_SECS
,   SUM(AUTHENTICATION_CONNECTION_ELAPSED_TIME_MCSEC) / 1000000 AS SLOW_AUTHENTICATION_CONNECTION_SECS
,   SUM(AUTHENTICATION_ELAPSED_TIME_MCSEC) / 1000000            AS SLOW_AUTHENTICATION_SECS
,   SUM(SQL_USER_ELAPSED_TIME_MCSEC) / 1000000                  AS SLOW_SQL_USER_SECS
FROM (SELECT
        CASE '%d'
        WHEN '1' THEN
            CAST(CAST((GEN_TS_LCT) AS DATE) AS TIMESTAMP(0))
            + CAST(HOUR((GEN_TS_LCT)) AS INTERVAL HOUR)
            + CAST(CAST(SUBSTRING(CAST(GEN_TS_LCT AS CHAR(26)) FROM 15 FOR 2) AS INTEGER) AS INTERVAL MINUTE)
        WHEN '10' THEN
            CAST(CAST((GEN_TS_LCT) AS DATE) AS TIMESTAMP(0))
            + CAST(HOUR((GEN_TS_LCT)) AS INTERVAL HOUR)
            + CAST(CAST(SUBSTRING(CAST(GEN_TS_LCT AS CHAR(26)) FROM 15 FOR 1) AS INTEGER) * 10 AS INTERVAL MINUTE)
        WHEN '60' THEN
            CAST(CAST((GEN_TS_LCT) AS DATE) AS TIMESTAMP(0))
            + CAST(HOUR((GEN_TS_LCT)) AS INTERVAL HOUR)
        END
        AS DATE_TIME
    ,   SESSION_START_TS_LCT
    ,   TOTAL_LOGIN_ELAPSED_TIME_MCSEC
    ,   LDAP_LOGIN_ELAPSED_TIME_MCSEC
    ,   SEARCH_CONNECTION_ELAPSED_TIME_MCSEC
    ,   SEARCH_ELAPSED_TIME_MCSEC
    ,   AUTHENTICATION_CONNECTION_ELAPSED_TIME_MCSEC
    ,   AUTHENTICATION_ELAPSED_TIME_MCSEC
    ,   SQL_USER_ELAPSED_TIME_MCSEC
    FROM
        MANAGEABILITY.INSTANCE_REPOSITORY.METRIC_SESSION_2
    WHERE
        SESSION_START_TS_LCT BETWEEN ? AND ?
        AND TOTAL_LOGIN_ELAPSED_TIME_MCSEC > 30000000
    ) AS A
GROUP BY
    DATE_TIME
ORDER BY
    DATE_TIME
FOR READ UNCOMMITTED ACCESS IN SHARE MODE''' % 1

