Report = 'Session/Aggregates 1-10-60 Min Intervals'
SQL = '''SELECT
    DATE_TIME
,   NODE_ID
,   TRIM(IP_ADDRESS_ID                ) AS "IP_ADDRESS_ID"
,   TRIM(PROCESS_NAME                 ) AS "PROCESS_NAME"
,   TRIM(SESSION_ID                   ) AS "SESSION_ID"
,   TRIM(USER_NAME                    ) AS "USER_NAME"
,   TRIM(ROLE_NAME                    ) AS "ROLE_NAME"
,   TRIM(CLIENT_NAME                  ) AS "CLIENT_NAME"
,   TRIM(CLIENT_USER_NAME             ) AS "CLIENT_USER_NAME"
,   TRIM(APPLICATION_NAME             ) AS "APPLICATION_NAME"
,   TRIM(DATASOURCE_NAME              ) AS "DATASOURCE_NAME"
,   SUM(TOTAL_ODBC_EXECUTION_TIME     ) AS "SUM_TOTAL_ODBC_EXECUTION_TIME"
,   SUM(TOTAL_ODBC_ELAPSED_TIME       ) AS "SUM_TOTAL_ODBC_ELAPSED_TIME"
,   SUM(TOTAL_INSERT_STMTS_EXECUTED   ) AS "SUM_TOTAL_INSERT_STMTS_EXECUTED"
,   SUM(TOTAL_DELETE_STMTS_EXECUTED   ) AS "SUM_TOTAL_DELETE_STMTS_EXECUTED"
,   SUM(TOTAL_UPDATE_STMTS_EXECUTED   ) AS "SUM_TOTAL_UPDATE_STMTS_EXECUTED"
,   SUM(TOTAL_SELECT_STMTS_EXECUTED   ) AS "SUM_TOTAL_SELECT_STMTS_EXECUTED"
,   SUM(TOTAL_CATALOG_STMTS           ) AS "SUM_TOTAL_CATALOG_STMTS"
,   SUM(TOTAL_PREPARES                ) AS "SUM_TOTAL_PREPARES"
,   SUM(TOTAL_EXECUTES                ) AS "SUM_TOTAL_EXECUTES"
,   SUM(TOTAL_FETCHES                 ) AS "SUM_TOTAL_FETCHES"
,   SUM(TOTAL_CLOSES                  ) AS "SUM_TOTAL_CLOSES"
,   SUM(TOTAL_EXECDIRECTS             ) AS "SUM_TOTAL_EXECDIRECTS"
,   SUM(TOTAL_ERRORS                  ) AS "SUM_TOTAL_ERRORS"
,   SUM(TOTAL_WARNINGS                ) AS "SUM_TOTAL_WARNINGS"
,   SUM(TOTAL_LOGIN_ELAPSED_TIME_MCSEC) AS "SUM_TOTAL_LOGIN_ELAPSED_TIME_MCSEC"
,   SUM(LDAP_LOGIN_ELAPSED_TIME_MCSEC ) AS "SUM_LDAP_LOGIN_ELAPSED_TIME_MCSEC"
,   MIN(SESSION_START_TS_LCT          ) AS "MIN_SESSION_START_TS_LCT"
,   MAX(SESSION_END_TS_LCT            ) AS "MAX_SESSION_END_TS_LCT"
FROM (SELECT
        CASE '%d'
        WHEN '1' THEN
            CAST(CAST((GEN_TS_LCT) AS DATE) AS TIMESTAMP(0))
            + CAST(HOUR((GEN_TS_LCT)) AS INTERVAL HOUR)
            + CAST(CAST(SUBSTRING(CAST(GEN_TS_LCT AS CHAR(26)) FROM 15 FOR 2) AS INTEGER) AS INTERVAL MINUTE)
        WHEN '10' THEN
            CAST(CAST((GEN_TS_LCT) AS DATE) AS TIMESTAMP(0))
            + CAST(HOUR((GEN_TS_LCT)) AS INTERVAL HOUR)
            + CAST(CAST(SUBSTRING(CAST(GEN_TS_LCT AS CHAR(26)) FROM 15 FOR 1) AS INTEGER)*10 AS INTERVAL MINUTE)
        WHEN '60' THEN
            CAST(CAST((GEN_TS_LCT) AS DATE) AS TIMESTAMP(0))
            + CAST(HOUR((GEN_TS_LCT)) AS INTERVAL HOUR)
        END
        AS DATE_TIME
    ,   *
    FROM
        MANAGEABILITY.INSTANCE_REPOSITORY.METRIC_SESSION_1
    WHERE
        GEN_TS_LCT  BETWEEN ? AND ?
    ) AS A
GROUP BY
    DATE_TIME
,   NODE_ID
,   IP_ADDRESS_ID
,   PROCESS_NAME
,   SESSION_ID
,   USER_NAME
,   ROLE_NAME
,   CLIENT_NAME
,   CLIENT_USER_NAME
,   APPLICATION_NAME
,   DATASOURCE_NAME
ORDER BY
    DATE_TIME
,   NODE_ID
,   IP_ADDRESS_ID
,   PROCESS_NAME
,   SESSION_ID
,   USER_NAME
,   ROLE_NAME
,   CLIENT_NAME
,   CLIENT_USER_NAME
,   APPLICATION_NAME
,   DATASOURCE_NAME
FOR READ UNCOMMITTED ACCESS IN SHARE MODE''' % 1

