Report = 'WMS/resources all intervals for time period'
SQL = '''SELECT
    GEN_TS_LCT
,   CURRENT_TS_LCT
,   UPSERT_TS_LCT
,   CPU_BUSY
,   MEMORY_USAGE
FROM
    MANAGEABILITY.INSTANCE_REPOSITORY.METRIC_WMS_RESOURCES_1
WHERE
    GEN_TS_LCT BETWEEN ? AND ?
ORDER BY
    GEN_TS_LCT
FOR READ UNCOMMITTED ACCESS IN SHARE MODE'''

